### PR TITLE
Handle nested MultipleInvalid exceptions.

### PR DESCRIPTION
**Pull request by cjw296**
Sorry, found another niggle...

Previously, this would result in an "AttributeError: can't set attribute" from trying to modify the path property on MultipleInvalid.

If you could do a release once this is merged, I'd be very grateful! :-)

### CODE REVIEW

**Comment by alecthomas** [comment]
Looks good. If you could squash the commits, I'll merge.

**Comment by cjw296** [comment]
Hmm, I'll try, but not sure I can from a pull request...

(I figured you might want to see the merge)

**Comment by alecthomas** [comment]
You just squash the commits and push -f the branch.

**Comment by cjw296** [comment]
Oh, git complained without the -f, I'll try that next time, for now, see #159.

**Pull request closed without merging**
