### PR TITLE
0.9.0

### PR DESCRIPTION
**Pull request by thatneat**
~20 backwards-compatible upgrades since the last release - the time is ripe! Minor version bump is appropriate as per [semver](http://semver.org) standard.

Please upload the new version to pypi when you merge this PR!

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
👍

**Comment by alecthomas** [comment]
👍

**Comment by alecthomas** [comment]
[Boom!](https://pypi.python.org/pypi/voluptuous/0.9.0)

Thanks guys. @tusharmakkar08 if you send me your PyPi username I'll add you as a maintainer there too.

**Comment by tusharmakkar08** [comment]
Sure.. It's **tusharmakkar08**

**Comment by alecthomas** [comment]
Done!

**Comment by tusharmakkar08** [comment]
Thanks 🍰

**Comment by thatneat** [comment]
:tada: thanks :balloon:

**Pull request merged**
