### PR TITLE
Display valid Enum values in Coerce

### PR DESCRIPTION
**Pull request by epenet**

### CODE REVIEW

**Comment by epenet** [comment]
Sample message: `"expected EntityCategory or one of ['config', 'diagnostic', 'system']"`

**Comment by epenet** [comment]
Sorry to chase, but is it likely to be considered? Or should it be handled inside Home Assistant?

**Comment by alecthomas** [comment]
Seems reasonable. Do the tests pass? I haven't set up CI since Circle died.

**Comment by epenet** [comment]
They do on my machine:
```console
nosetests
.......................................................................................................................................................................................
----------------------------------------------------------------------
Ran 183 tests in 0.088s

OK
```

**Comment by epenet** [comment]
Added tests:
```console
nosetests --with-coverage --cover-package=voluptuous
........................................................................................................................................................................................
Name                           Stmts   Miss  Cover
--------------------------------------------------
voluptuous/__init__.py             6      0   100%
voluptuous/error.py               78      2    97%
voluptuous/humanize.py            22      7    68%
voluptuous/schema_builder.py     509     18    96%
voluptuous/util.py                63      7    89%
voluptuous/validators.py         460     13    97%
--------------------------------------------------
TOTAL                           1138     47    96%
----------------------------------------------------------------------
Ran 184 tests in 0.139s

OK
```

**Comment by alecthomas** [comment]
Would you mind formatting this without the list brackets? eg. `one of 1, 2, 3` or one of 'one', 'two', 'three'`

**Comment by epenet** [comment]
Adjusted without the brackets, and added tests for a string enum.

```console
nosetests --with-coverage --cover-package=voluptuous
........................................................................................................................................................................................
Name                           Stmts   Miss  Cover
--------------------------------------------------
voluptuous/__init__.py             6      0   100%
voluptuous/error.py               78      2    97%
voluptuous/humanize.py            22      7    68%
voluptuous/schema_builder.py     509     18    96%
voluptuous/util.py                63      7    89%
voluptuous/validators.py         460     13    97%
--------------------------------------------------
TOTAL                           1138     47    96%
----------------------------------------------------------------------
Ran 184 tests in 0.132s

OK
```

**Comment by alecthomas** [comment]
Perfect, thank you so much!

**Comment by epenet** [comment]
Thanks 👍

**Comment by epenet** [comment]
Let me know when the release is available...

**Comment by epenet** [comment]
Any luck with the release ?

**Comment by jamesbraid** [comment]
This broke for py2.7, homepage still lists py2.7 as being supported... what to do?

**Pull request merged**
