### PR TITLE
Always evaluate {} as {}

### LINKED ISSUE #198: [] should evaluate to an empty list, not any list
```python
>>> from voluptuous import Schema
>>> Schema({})({})
{}
>>> Schema({})({'foo': 1})
Traceback (most recent call last):
...
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['foo']
>>> Schema(int)(5)
5
>>> Schema(2)(5)
Traceback (most recent call last):
...
voluptuous.error.MultipleInvalid: not a valid value
>>> Schema([])([])
[]
>>> Schema([])([1])  # shouldn't this throw error?
[1]
```

Wouldn't it be logical to evaluate `list` for any list and `[]` for an exact value (an empty list)?

### PR DESCRIPTION
**Pull request by tuukkamustonen**
Fixes #198

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
Hey @tuukkamustonen , 

Travis build is failing. Please update the PR. 

Thanks

**Comment by tuukkamustonen** [comment]
@tusharmakkar08 Fixed, but I set `+IGNORE_EXCEPTION_DETAIL` doctest flag in `setup.cfg`.

Note that this is backwards-incompatible change: `Schema({}, extra=ALLOW_EXTRA)` does not work anymore, one should use ´Schema(dict)` instead. 

I see there's no `CHANGELOG` in this project, have you thought about adding one?

**Comment by tusharmakkar08** [comment]
Hey @tuukkamustonen 

It is preferred not to set `+IGNORE_EXCEPTION_DETAIL` since the content of exception is also important for `voluptuous`. We even have specialised modules like `humanize.py`  to make errors more reader-friendly. I would suggest to use `try-catch` instead of setting the flag.

Currently, there's no `CHANGELOG` in this project. It would be great if you can add it via this PR itself. 

Thanks.

**Comment by tuukkamustonen** [comment]
@tusharmakkar08 Alright, sounds reasonable. I've been a bit busy but I'll update PR tomorrow!

**Comment by tuukkamustonen** [comment]
@tusharmakkar08 Removed the doctest flag and added `CHANGELOG.md`. I have a convention of marking Changes/New features/Fixes under sub-categories, but some use prefixes, and some don't indicate category in any way. Hope this syntax suits you?

**Comment by alecthomas** [comment]
I'm a little bit concerned about the backwards incompatibility, thoughts @tusharmakkar08?

**Comment by tusharmakkar08** [comment]
I was also a bit vehement initially but I guess since we merged https://github.com/alecthomas/voluptuous/issues/201 which solves https://github.com/alecthomas/voluptuous/issues/198, prioritising consistency over the backward incompatibility of list, we should go ahead with this too. The next release we can mark as MAJOR release according to [semantic versioning](http://semver.org/) standards. What do you think @alecthomas ?

**Comment by alecthomas** [comment]
That's true. A major version bump sounds like a good idea too. +1

**Comment by tuukkamustonen** [comment]
I think semantic versioning is a bit over-engineered. I see no real need in separating new features (MINOR) and bug fixes (PATCH). Theoretically it's nice, but I don't see much use of it.

Many projects use the following semantics:

- MAJOR is for architecture and is bumped only when bigger changes are introduced,
- MINOR is for backwards-incompatible changes, and
- PATCH is for bugfixes and new features.

The reasoning is that adding new features doesn't break your code, so those changes are safe to include in a mere PATCH bump.

I don't know if this versioning scheme has a name, but I think it's pretty common and would suggest it also here instead of true semantic versioning (as in semver.org).

**Comment by tuukkamustonen** [comment]
About the changes: there is still a chance to revert the list change and decline this one, too.

Even with these changes, it's a bit weird that while `[]` is evaluated as value (matches only `[]`), and `[2, 3]` is evaluated as schema instead (matches `[2, 3]`, `[3, 2]`, even `[3, 3, 2, 3]`) and you need `Equal([2, 3])` to match a list of `[2, 3]`.

Similarly for dicts, `{}` now evaluates as value but `{...}` turns into schema. There, you can either just `{'foo': 1}` if you're inside a schema that sets `extra=PREVENT_EXTRA`, or `Equal({'foo': 1})` (works always) or `Schema({}, extra=PREVENT_EXTRA)`.

The "perfect" solution would be to by default always evaluate per value and require `Schema(...)` when user wants schema-style validation. For example, `[2, 3]` would match only `[2, 3]` and `Schema([2, 3])` would match `[2, 3]`, `[3, 2]` and even `[3, 3, 2, 3]`. Similarly, `{'foo': 1}` would match only `{'foo': 1}` and `Schema({'foo': 1})` would follow the old behavior.

However, that would bring boilerplate and kill the voluptuous selling point so I'm just theorizing here...

In the end, I do think this PR and the list PR that was merged do improve the situation a bit, but I feel there's something in the design that forces the concept a bit confusing.

**Comment by tusharmakkar08** [comment]
Hey @tuukkamustonen 

We have been following Semantic Versioning since the beginning of project since it ensures the backward compatibility (Moving from `0.8.11` to `0.9.3` was a major change but since it was backward compatible, we marked it as minor upgrade only). 

Regarding the changes related to https://github.com/alecthomas/voluptuous/issues/198, we knew that the changes were backward incompatible and we had a discussion over there regarding it. I also agree with the `perfect` solution which you mentioned (But the boilerplate code 🌵 🔨). @alecthomas What do you think about this? Should we revert the old merged PR, merge this PR and mark this as major release or strive towards the perfect solution ? 

- TM

**Comment by tusharmakkar08** [comment]
@alecthomas : Should we proceed with this and major version release?

**Comment by tusharmakkar08** [comment]
@alecthomas : I am planning to merge it (since I feel it encourages consistency) by today EOD. Please let me know if you have any objections. 

Thanks.

**Pull request merged**
