### PR TITLE
Rebuild docs

### PR DESCRIPTION
**Pull request by tuukkamustonen**
Quite a huge merge + 1 tune commit + 1 rebuild commit.

Having docs in master branch would allow updating docs inside standard fix/feature PRs.

### CODE REVIEW

**Comment by alecthomas** [comment]
I don't think that's how gh-pages work. For pages to get updated they have to be up on that branch. So I don't think this PR is what we want (IIUC).

**Comment by tuukkamustonen** [comment]
@alecthomas Sorry for being such brief. What I meant is that you have to make a rebuild-commit in gh-pages anyway. So while at it you could just merge master into gh-pages on the same go.

**Comment by tusharmakkar08** [comment]
Hey @tuukkamustonen : Checkout gh-pages branch, then merge your local master (after fetching upstream) into gh-pages. Then update the sphinx doc and html. Verify the modified index.html and then create a new PR to gh-pages branch itself not to master. 
I am closing this PR for now.

**Comment by tuukkamustonen** [comment]
@tusharmakkar08 I thought I did that. And this PR was "into alecthomas:gh-pages from tuukkamustonen:gh-pages". Can you point out in detail where I went wrong?

**Comment by tusharmakkar08** [comment]
I changed the base branch to `alecthomas:gh-pages` from `alecthomas:master`. Just wanted to make sure if you did everything correctly. Does `index.html` shows `Equal` class properly and isn't breaking any other element ? I checked from the code and it does have `Equal` class . Let me know if it renders properly. 
Reopening the PR.

**Comment by tuukkamustonen** [comment]
Ah alright, so I had it in fault in the first place. Forgot to check that, sorry!

I merged latest master again (containing Unordered) and rebuild docs the second time. Everything looks good as far as I can tell.

**Pull request merged**
