### PR TITLE
Adding Equality between schemas

### PR DESCRIPTION
**Pull request by tusharmakkar08**
Fixes https://github.com/alecthomas/voluptuous/issues/208

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
@alecthomas : Since `__repr__` was the combination of object and extras and schemas, `__eq__` was giving wrong in cases `Required` etc were present. Hence I proceeded with making a `__str__` for `Schema`.  Now it'll satisfy cases mentioned by @AndreaCrotti .

**Comment by alecthomas** [comment]
Ok... I feel like this could use some tests though.

**Comment by tusharmakkar08** [comment]
Aren't doctests sufficient ?

**Comment by alecthomas** [comment]
I was thinking more tests for deeply nested schemas, using things like `Any()` etc.

**Comment by tusharmakkar08** [comment]
Hmm.. 
I have couple of concerns: 

-  For scenarios like this:

       schema = Schema(Any(None, int))
       schema1 = Schema(Any(int, None))

Do we need to have `schema==schema1` as True? If yes, then the current logic won't work.
- I'll add more tests using Nested schemas and stuff. I will create a separate PR for the same, instead of reverting this PR. Is it fine? 

Thanks

**Comment by alecthomas** [comment]
Yeah, I'm not sure about Any (and possibly others) which is kind of why I brought it up. It's probably fine as-is though, for 99% of cases.

**Comment by tusharmakkar08** [comment]
Cool 👍

**Pull request merged**
