### PR TITLE
Add pytest.ini and tox.ini to sdist

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by KapJI** [comment]
Can you tell why is this useful? Why don't just checkout full repo if you want to run these checks?

**Comment by mtelka** [comment]
I'm packaging `voluptuous` for OpenIndiana.  During the packaging we run tests.  By default we use sdists as a source for packaging and tests are run automatically.  `tox.ini` is useful to get test dependencies too.  If there is something missing somewhere we need to do some extra manual work.  Of course, we can use github tarballs instead of sdist (actually we currently [do exactly that](https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/python/voluptuous/python-integrate-project.conf)), but there are two problems with github tarballs:
1. some manual work is needed (you can see it in our `python-integrate-project.conf` file),
2. github tarballs are [not reliable and could change without notice](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/), so reproducible builds are not possible.

Thank you.

**Comment by KapJI** [comment]
Sounds reasonable, thank you.

**Comment by alecthomas** [comment]
Agreed, makes sense, thanks!

**Comment by mtelka** [comment]
I do not need new release with these ini files added only.  Thanks.

**Comment by alecthomas** [comment]
Next release.

**Pull request merged**
