### PR TITLE
Add python_requires so package installers know this requires 3.7 or newer

### PR DESCRIPTION
**Pull request by cjw296**
Also remove some stale classifiers.

Happy to add any release notes or whatever to get a release out.

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

**Comment by cjw296** [comment]
@alecthomas - awesome, thanks. Now can I nag you for a voluptuous 0.14.1 release?

**Comment by spacegaier** [comment]
> @alecthomas - awesome, thanks. Now can I nag you for a voluptuous 0.14.1 release?

I just published a new release

**Comment by alecthomas** [comment]
Thanks Philip, appreciate it!

**Comment by cjw296** [comment]
@spacegaier - any chance you could yank the 0.14.0 release? Colleagues have pointed out that pip will still pick it on Python 2 and 3.6 :-/

**Comment by spacegaier** [comment]
> @spacegaier - any chance you could yank the 0.14.0 release? Colleagues have pointed out that pip will still pick it on Python 2 and 3.6 :-/

Does that have any side effects e.g. for people that already pulled that version? Never had to yank a version on PyPi. Would need to read up on how to do that to begin with...

**Comment by alecthomas** [comment]
I don't think that would be a good idea would it? Anyone depending on that release will have their build broken.

**Comment by cjw296** [comment]
I mean, not yanking it means every Python 3.6 or earlier user still has to deal with this bug forever more with ugly workarounds. I'm not 100% sure of the semantics of yanking, it may leave the release up there for those explicitly requesting it, but even if not, it doesn't feel like a third point upgrade to fix broken built is a bad trade off for every 3.6 and  earlier user having to cargo cult a workaround in their package config.

**Comment by alecthomas** [comment]
I don't think that logic holds does it? If they're on 3.6 it would never have worked and they wouldn't have pinned it, and if they're not pinned they'll get the next version.

**Comment by alecthomas** [comment]
Ah I see what you're saying. It's because it's the last version valid for 3.6/2.7.

**Comment by cjw296** [comment]
Yep, currently breaking CI for a handful of internal packages where they work, ;cos 2.7 or 3.6 versions are picking up 0.14.0 and blowing up

**Comment by alecthomas** [comment]
Yanked it. PyPi says it's still usable if pinned, so that's good.

**Comment by cjw296** [comment]
Many thanks! :-)

**Pull request merged**
