### PR TITLE
Stop supporting 3.2

### PR DESCRIPTION
**Pull request by AndreaCrotti**
I originally did this in this pull request https://github.com/alecthomas/voluptuous/pull/223

but maybe better to do it separately, since it's not really related..

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
And by the way there is small discrepancy between travis.yml and the supported languages.
travis also runs on Python 2.6 but 2.6 is not declared in the setup.py..

Should we just remove it from travis so one less thing to check?
(also tox is not declared for all the versions but I guess that's not as important since it's travis what matters most)

**Comment by alecthomas** [comment]
What's the purpose of removing 3.2?

**Comment by AndreaCrotti** [comment]
@alecthomas well the immediate reason is that it did't work with pytest.
The "deeper" reason is maybe that noone uses it really, and in fact 3.1 and 3.2 are also not supported by many other projects.

**Comment by tusharmakkar08** [comment]
@AndreaCrotti I am also not in favour of removing Python 3.2 since some projects might be using Voluptuous with Python 3.2

**Comment by AndreaCrotti** [comment]
Yes well it could be sure, overall the number of projects using 3.2 is tiny though, they didn't even have unicode literals so whoever ported ported to >=3.3

Anyway as you want, but without this we can't use pytest then..
On Pypi you can also see that packages supporting 3.1 and 3.2 are a vastly lower number, so most people even if they want can't use Python 3.2 in production anyway.

```
Programming Language :: Python
2 (13981) 2.3 (74) 2.4 (416) 2.5 (1298) 2.6 (10570) 2.7 (24714) 3 (18200) 3.0 (686) 3.1 (1159) 3.2 (4712) 3.3 (11758) 3.4 (13730) 3.5 (7870) 3.6 (137) Implementation (3918)
```

**Comment by AndreaCrotti** [comment]
What would you like to do about this?

I understand that it's nice to support all the versions, but I honestly doubt anyone cares about Python 3.2, if someone managed to switch to Python3 they have no reason to go <=3.3...

And well if you don't want to do that then I'll have to close the pytest PR as well since py.test explicitly doesn't support Python 3.2..(and that says a lot I think given how pytest is widespread)

**Comment by tusharmakkar08** [comment]
I don't think that moving from nosetests to py.test provides significant advantages. @alecthomas you can take the final call on this.

**Comment by alecthomas** [comment]
Yes, I agree... thanks for the effort though @AndreaCrotti, sorry it was for naught.

**Pull request closed without merging**
