### PR TITLE
Readme updated to incorporate usage of Email

### PR DESCRIPTION
**Pull request by tusharmakkar08**
Readme updated

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
@alecthomas : Any comments on this?

**Comment by alecthomas** [comment]
I don't think it's necessary to put all validators in the README. In fact the Url one should probalby not be there, I'll get rid of it.

What might be better would be a simple summary of some frequently used validators eg. `Some common validators include Url, Email, ....`

**Comment by tusharmakkar08** [comment]
I personally feel that with examples people can understand better. @alecthomas What do you think about  hosting documentation using sphinx/any other documentation generator instead of github `md` files like we are doing currently ?

**Comment by alecthomas** [comment]
Yeah, that seems like a better idea than over-using the README.

**Comment by tusharmakkar08** [comment]
@alecthomas Should I create an issue corresponding to that ?

**Comment by alecthomas** [comment]
Yep, please do.

**Pull request closed without merging**
