### PR TITLE
Enable python 3.10 in github actions

### PR DESCRIPTION
**Pull request by epenet**
Follow-up to #457
Needs #422

### CODE REVIEW

**Comment by epenet** [comment]
Or maybe we just drop coverage from the py310 session in tox...

**Comment by epenet** [comment]
Of maybe we do need to switch to pytest if the issue is inside nosetest

**Comment by spacegaier** [comment]
> Of maybe we do need to switch to pytest if the issue is inside nosetest

I think switching makes sense, also given that `nose` is now deprecated. And if we have to switch `pytest` makes probably more sense than `nose2`.

**Comment by spacegaier** [comment]
Superseded by https://github.com/alecthomas/voluptuous/pull/464

**Pull request closed without merging**
