### PR TITLE
move to pytest

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Change from nose to pytest related to #221

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti  

Travis build is failing. Please update the PR.

Thanks

**Comment by AndreaCrotti** [comment]
only test that fails is now for Python 3.2
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/py.test", line 7, in <module>
    from pytest import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pytest.py", line 27, in <module>
    _preloadplugins() # to populate pytest.* namespace so help(pytest) works
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/_pytest/config.py", line 85, in _preloadplugins
    _preinit.append(get_config())
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/_pytest/config.py", line 94, in get_config
    pluginmanager.import_plugin(spec)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/_pytest/config.py", line 405, in import_plugin
    __import__(importspec)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/_pytest/python.py", line 1395
    plus_minus = u'{0} \u00b1 {1}'.format(self.expected, vetted_tolerance)

```

Looks like pytest doesn't like Python 3.2.
I think many packages don't and noone really uses it anyway, could we maybe not just drop Python 3.2?

**Comment by AndreaCrotti** [comment]
Coveralls is probably just a slightly different setting I have to tune to make it happy..

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti 

Few of the tests are failing in travis and the coverage is also reduced significantly. Please fix the tests and get coverage up.

Thanks

**Comment by alecthomas** [comment]
Closing, see #225.

**Pull request closed without merging**
