### PR TITLE
add Schema.infer method

### PR DESCRIPTION
**Pull request by dtao**
This introduces the class method Schema.infer, to infer a Schema from
concrete data. This will be useful for converting existing known-good
data (e.g. API responses) into enforceable schemas.

### CODE REVIEW

**Comment by dtao** [comment]
I have written code like this for my own projects and found it useful. I figured it might be nice to add it to the library itself.

Forgive me if this functionality already exists. I couldn't find it!

**Comment by svisser** [comment]
@dtao aside from the possible discussion of whether this logic should be part of this library, I wonder whether it should take multiple samples to infer the schema?

Because it may be that a schema "should be" a list of multiple values (e.g., `Optional("gender"): In(["male", "female", "other"])` rather than `Optional("gender"): "male"`).

**Comment by tusharmakkar08** [comment]
I guess this functionality can be added to the library. Also, I agree with the point @svisser made.

@dtao Can we have `Schema.infer` taking multiple values?

**Comment by dtao** [comment]
I'm open to changing things, but from @svisser's comment I think we might not be on the same page re: what this method does (or should do). This is certainly at least partially my fault for not being more thorough in the PR description (and perhaps in the docstring as well).

The way the method works in the current implementation isn't that `"male"` gets converted to `"male"`; rather, it get converted to `str`. The use case I have in mind is that you have a known-good object (what is sometimes called "golden data")—perhaps already available in a handy JSON file—and you want to create a schema to validate objects that look *like* that object, i.e. have the same keys, with values of the same types.

So:

```python
s = Schema.infer({
    'int': 42,
    'str': 'foo',
    'bool': True
})

s({'int': 27, 'str': 'bar', 'bool': False})  # valid
```

I don't personally think it's necessary (or even feasible) for this method to provide a comprehensive way of inferring every feature already supported by the `Schema` class. It seems the scenario @svisser had in mind was the case of _enums_ (`["male", "female", "other"]`); I am personally fine with a limitation of this method being that you can't infer those, or ranges, or callables, or any number of other things. But it *does* provide a very easy way of, for example, quickly scaffolding a suite of API regression tests.

**Comment by alecthomas** [comment]
I think it's fine to add this, but if you could add something like "Note: only very basic inference is supported".

**Comment by dtao** [comment]
@alecthomas I added the note that you suggested. I thought about being a bit more verbose and explaining more, but hopefully the example in the docstring with the note together will do most of the work to manage expectations.

**Comment by alecthomas** [comment]
Yeah, that's great, thanks :)

**Pull request merged**
